# Generated by Django 5.1.3 on 2024-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_anime', models.CharField(default='Desconocido', max_length=50)),
                ('episodios', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('fecha', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='Finalizado', max_length=50)),
                ('generos', models.TextField()),
                ('sinopsis', models.TextField(default='Sin sinopsis disponible.')),
            ],
        ),
    ]
